'use client';

import { useState } from 'react';
import { Copy, Loader2, Sparkles, Check } from 'lucide-react';
import { Modal } from '@/components/ui/modal';
import { useToast } from '@/components/ui/toast';

function todayLabel(): string {
  return new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function AICampaignReportButton() {
  const toast = useToast();
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const [report, setReport] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  async function generate() {
    if (loading) return;
    setLoading(true);
    try {
      const res = await fetch('/api/intelligence/campaign-report', {
        method: 'POST',
      });
      if (!res.ok) throw new Error('failed');
      const data = (await res.json()) as { report?: string };
      if (!data.report) throw new Error('empty');
      setReport(data.report);
      setOpen(true);
    } catch (e) {
      console.error('AI campaign report failed', e);
      toast.show("Couldn't generate report. Try again in a moment.", 'error');
    } finally {
      setLoading(false);
    }
  }

  async function copy() {
    if (!report) return;
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('clipboard failed', e);
      toast.show("Couldn't copy to clipboard.", 'error');
    }
  }

  return (
    <>
      <button
        type="button"
        onClick={generate}
        disabled={loading}
        className="flex w-full items-center justify-center gap-2 rounded-lg border border-accent bg-transparent px-4 py-2.5 text-xs font-medium text-accent transition-colors hover:bg-accent/10 disabled:cursor-not-allowed disabled:opacity-60"
      >
        {loading ? (
          <>
            <Loader2 className="h-4 w-4 animate-spin" />
            ✦ Analyzing campaign data…
          </>
        ) : (
          <>
            <Sparkles className="h-4 w-4" />
            Generate full AI report
          </>
        )}
      </button>

      <Modal
        isOpen={open}
        onClose={() => setOpen(false)}
        title="AI Campaign Report"
        subtitle={
          <span className="inline-flex items-center gap-1">
            <Sparkles className="h-3 w-3 text-accent" />
            Generated by NiBL Intelligence · {todayLabel()}
          </span>
        }
        maxWidth="640px"
        footer={
          <div className="flex flex-wrap items-center justify-end gap-2">
            <button
              type="button"
              onClick={copy}
              className="inline-flex items-center gap-1.5 rounded-lg border border-foreground bg-background px-3 py-1.5 text-xs"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-success" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  Copy to clipboard
                </>
              )}
            </button>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="rounded-lg border border-foreground bg-background px-3 py-1.5 text-xs"
            >
              Close
            </button>
          </div>
        }
      >
        {report ? (
          <div className="space-y-3 text-[13px] leading-[1.8] text-foreground">
            {report.split(/\n\s*\n/).map((para, i) => (
              <p key={i}>{para}</p>
            ))}
          </div>
        ) : null}
      </Modal>
    </>
  );
}
